categorydir: /blog/category
tagdir: /blog/tag
blogdir: /blog
permalink: /blog/:year/:month/:title/
markdown: rdiscount

include:
  - .htaccess
exclude:
  - cv/muller_cv.tex
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Procfile
  - Rakefile
  - readme.markdown

rdiscount:
  extensions: [smart]

assets:
  compress:
    css:  sass
