auto: false
categorydir: /blog/category
tagdir: /blog/tag
blogdir: /blog
permalink: /blog/:year/:month/:title/
markdown: rdiscount

include:
  - .htaccess
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - readme.markdown

rdiscount:
  extensions: [smart]
